#include "codegen.h"
#include "c_emitter.h"
#include "expression_gen.h"
#include "statement_gen.h"
#include "declaration_gen.h"
#include "../utils/utils.h"
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>

// 创建代码生成器
CodeGenerator* codegen_create(FILE* output, SymbolTable* symbol_table) {
    CodeGenerator* cg = malloc(sizeof(CodeGenerator));
    if (!cg) return NULL;
    
    cg->output = output;
    cg->code = sb_create();
    cg->symbol_table = symbol_table;
    cg->indent_level = 0;
    cg->in_function = false;
    cg->in_loop = false;
    cg->generated_functions = vector_create(free_direct);
    cg->generated_structs = vector_create(free_direct);
    cg->errors = vector_create(free_direct);
    cg->warnings = vector_create(free_direct);
    cg->needs_runtime = false;
    cg->runtime_functions = hash_map_create(free_direct, free_direct);
    
    return cg;
}

// 释放代码生成器
void codegen_free(CodeGenerator* cg) {
    if (!cg) return;
    
    sb_free(cg->code);
    vector_free(cg->generated_functions);
    vector_free(cg->generated_structs);
    vector_free(cg->errors);
    vector_free(cg->warnings);
    hash_map_free(cg->runtime_functions);
    free(cg);
}

// 生成整个程序的代码
bool codegen_generate(CodeGenerator* cg, Node* program) {
    if (!cg || !program || program->type != NODE_PROGRAM) {
        return false;
    }
    
    // 生成文件头
    codegen_emit_line(cg, "// Generated by C+ compiler");
    codegen_emit_line(cg, "#include <stdio.h>");
    codegen_emit_line(cg, "#include <stdlib.h>");
    codegen_emit_line(cg, "#include <stdbool.h>");
    codegen_emit_line(cg, "#include <string.h>");
    codegen_emit_line(cg, "");
    
    // 如果需要运行时库，包含运行时头文件
    if (codegen_needs_runtime(cg)) {
        codegen_include_runtime(cg);
    }
    
    // 生成所有声明
    bool success = true;
    for (size_t i = 0; i < vector_size(program->program.declarations); i++) {
        Node* decl = vector_get(program->program.declarations, i);
        if (!codegen_generate_node(cg, decl)) {
            success = false;
        }
    }
    
    // 将生成的代码写入输出文件
    if (success) {
        fprintf(cg->output, "%s", sb_to_string(cg->code));
    }
    
    return success && !codegen_has_errors(cg);
}

// 生成单个节点的代码
bool codegen_generate_node(CodeGenerator* cg, Node* node) {
    if (!cg || !node) return false;
    
    switch (node->type) {
        // 声明
        case NODE_PROGRAM:
            return codegen_generate(cg, node);
        case NODE_FUNCTION_DECL:
            return codegen_function_decl(cg, node);
        case NODE_VAR_DECL:
            return codegen_variable_decl(cg, node);
        case NODE_STRUCT_DECL:
            return codegen_struct_decl(cg, node);
        case NODE_ENUM_DECL:
            return codegen_enum_decl(cg, node);
            
        // 语句
        case NODE_BLOCK_STMT:
            return codegen_block_stmt(cg, node);
        case NODE_EXPR_STMT:
            return codegen_expr_stmt(cg, node);
        case NODE_IF_STMT:
            return codegen_if_stmt(cg, node);
        case NODE_FOR_STMT:
            return codegen_for_stmt(cg, node);
        case NODE_WHILE_STMT:
            return codegen_while_stmt(cg, node);
        case NODE_MATCH_STMT:
            return codegen_match_stmt(cg, node);
        case NODE_RETURN_STMT:
            return codegen_return_stmt(cg, node);
        case NODE_BREAK_STMT:
            return codegen_break_stmt(cg, node);
        case NODE_CONTINUE_STMT:
            return codegen_continue_stmt(cg, node);
            
        // 表达式
        case NODE_BINARY_EXPR:
            return codegen_binary_expr(cg, node);
        case NODE_UNARY_EXPR:
            return codegen_unary_expr(cg, node);
        case NODE_CALL_EXPR:
            return codegen_call_expr(cg, node);
        case NODE_METHOD_CALL_EXPR:
            return codegen_method_call_expr(cg, node);
        case NODE_FIELD_ACCESS_EXPR:
            return codegen_field_access_expr(cg, node);
        case NODE_ARRAY_ACCESS_EXPR:
            return codegen_array_access_expr(cg, node);
        case NODE_LITERAL_EXPR:
            return codegen_literal_expr(cg, node);
        case NODE_IDENTIFIER_EXPR:
            return codegen_identifier_expr(cg, node);
        case NODE_IF_EXPR:
            return codegen_if_expr(cg, node);
        case NODE_ARRAY_EXPR:
            return codegen_array_expr(cg, node);
        case NODE_STRUCT_EXPR:
            return codegen_struct_expr(cg, node);
        case NODE_CLOSURE_EXPR:
            return codegen_closure_expr(cg, node);
            
        default:
            codegen_error(cg, "Unsupported node type in code generation", 
                         node->line, node->column);
            return false;
    }
}

// ===== 工具函数 =====

// 发射代码（不带换行）
void codegen_emit(CodeGenerator* cg, const char* format, ...) {
    if (!cg || !format) return;
    
    va_list args;
    va_start(args, format);
    
    char buffer[1024];
    vsnprintf(buffer, sizeof(buffer), format, args);
    sb_append(cg->code, buffer);
    
    va_end(args);
}

// 发射代码行（带缩进和换行）
void codegen_emit_line(CodeGenerator* cg, const char* format, ...) {
    if (!cg || !format) return;
    
    // 缩进
    for (int i = 0; i < cg->indent_level; i++) {
        sb_append(cg->code, "    ");
    }
    
    va_list args;
    va_start(args, format);
    
    char buffer[1024];
    vsnprintf(buffer, sizeof(buffer), format, args);
    sb_append(cg->code, buffer);
    sb_append(cg->code, "\n");
    
    va_end(args);
}

// 增加缩进
void codegen_indent_increase(CodeGenerator* cg) {
    if (cg) cg->indent_level++;
}

// 减少缩进
void codegen_indent_decrease(CodeGenerator* cg) {
    if (cg && cg->indent_level > 0) cg->indent_level--;
}

// ===== 类型映射 =====

// 将C+类型映射到C类型
const char* codegen_type_to_c_type(Type* type) {
    if (!type) return "void";
    
    switch (type->kind) {
        case TYPE_VOID: return "void";
        case TYPE_INT8: return "int8_t";
        case TYPE_INT16: return "int16_t";
        case TYPE_INT32: return "int32_t";
        case TYPE_INT64: return "int64_t";
        case TYPE_UINT8: return "uint8_t";
        case TYPE_UINT16: return "uint16_t";
        case TYPE_UINT32: return "uint32_t";
        case TYPE_UINT64: return "uint64_t";
        case TYPE_FLOAT32: return "float";
        case TYPE_FLOAT64: return "double";
        case TYPE_BOOL: return "bool";
        case TYPE_CHAR: return "char";
        case TYPE_STRING: return "char*";
        case TYPE_ARRAY:
            // 数组类型：element_type[size]
            {
                static char buffer[128];
                const char* element_type = codegen_type_to_c_type(type->array.element_type);
                if (type->array.array_size >= 0) {
                    snprintf(buffer, sizeof(buffer), "%s[%d]", element_type, type->array.array_size);
                } else {
                    snprintf(buffer, sizeof(buffer), "%s[]", element_type);
                }
                return buffer;
            }
        case TYPE_SLICE:
            // 切片类型：使用运行时库的Slice结构
            {
                static char buffer[128];
                const char* element_type = codegen_type_to_c_type(type->slice.element_type);
                snprintf(buffer, sizeof(buffer), "Slice_%s", element_type);
                return buffer;
            }
        case TYPE_STRUCT:
            return type->named.type_name ? type->named.type_name : "struct";
        default:
            return "void";
    }
}

// 将C+运算符映射到C运算符
const char* codegen_operator_to_c_operator(TokenType operator) {
    switch (operator) {
        case TOKEN_PLUS: return "+";
        case TOKEN_MINUS: return "-";
        case TOKEN_STAR: return "*";
        case TOKEN_SLASH: return "/";
        case TOKEN_PERCENT: return "%";
        case TOKEN_EQEQ: return "==";
        case TOKEN_NEQ: return "!=";
        case TOKEN_LT: return "<";
        case TOKEN_GT: return ">";
        case TOKEN_LTEQ: return "<=";
        case TOKEN_GTEQ: return ">=";
        case TOKEN_AND: return "&&";
        case TOKEN_OR: return "||";
        case TOKEN_NOT: return "!";
        case TOKEN_AMP: return "&";
        case TOKEN_PIPE: return "|";
        case TOKEN_CARET: return "^";
        case TOKEN_TILDE: return "~";
        case TOKEN_LSHIFT: return "<<";
        case TOKEN_RSHIFT: return ">>";
        default: return "";
    }
}

// ===== 错误处理 =====

void codegen_error(CodeGenerator* cg, const char* message, int line, int column) {
    if (!cg || !message) return;
    
    StringBuilder* sb = sb_create();
    sb_append_format(sb, "[Line %d, Column %d] CodeGen Error: %s", line, column, message);
    
    char* error_msg = sb_to_string(sb);
    vector_push(cg->errors, error_msg);
    sb_free(sb);
}

void codegen_warning(CodeGenerator* cg, const char* message, int line, int column) {
    if (!cg || !message) return;
    
    StringBuilder* sb = sb_create();
    sb_append_format(sb, "[Line %d, Column %d] CodeGen Warning: %s", line, column, message);
    
    char* warning_msg = sb_to_string(sb);
    vector_push(cg->warnings, warning_msg);
    sb_free(sb);
}

bool codegen_has_errors(const CodeGenerator* cg) {
    return cg && !vector_is_empty(cg->errors);
}

void codegen_print_errors(const CodeGenerator* cg) {
    if (!cg || vector_is_empty(cg->errors)) {
        return;
    }
    
    printf("Code Generation Errors:\n");
    for (size_t i = 0; i < vector_size(cg->errors); i++) {
        char* error = vector_get(cg->errors, i);
        printf("  %s\n", error);
    }
}

// ===== 运行时库集成 =====

void codegen_include_runtime(CodeGenerator* cg) {
    if (!cg) return;
    
    codegen_emit_line(cg, "// C+ Runtime Library");
    codegen_emit_line(cg, "#include \"cplus_runtime.h\"");
    codegen_emit_line(cg, "");
    cg->needs_runtime = true;
}

bool codegen_needs_runtime(const CodeGenerator* cg) {
    return cg && cg->needs_runtime;
}